// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: sfu_rpc.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_sfu_5frpc_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_sfu_5frpc_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3019000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3019001 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_sfu_5frpc_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_sfu_5frpc_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxiliaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[10]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_sfu_5frpc_2eproto;
namespace sfu_rpc {
class AddPublisherReq;
struct AddPublisherReqDefaultTypeInternal;
extern AddPublisherReqDefaultTypeInternal _AddPublisherReq_default_instance_;
class AddPublisherRsp;
struct AddPublisherRspDefaultTypeInternal;
extern AddPublisherRspDefaultTypeInternal _AddPublisherRsp_default_instance_;
class CreateRoomReq;
struct CreateRoomReqDefaultTypeInternal;
extern CreateRoomReqDefaultTypeInternal _CreateRoomReq_default_instance_;
class CreateRoomRsp;
struct CreateRoomRspDefaultTypeInternal;
extern CreateRoomRspDefaultTypeInternal _CreateRoomRsp_default_instance_;
class DestroyRoomReq;
struct DestroyRoomReqDefaultTypeInternal;
extern DestroyRoomReqDefaultTypeInternal _DestroyRoomReq_default_instance_;
class DestroyRoomRsp;
struct DestroyRoomRspDefaultTypeInternal;
extern DestroyRoomRspDefaultTypeInternal _DestroyRoomRsp_default_instance_;
class KeyframeRequest;
struct KeyframeRequestDefaultTypeInternal;
extern KeyframeRequestDefaultTypeInternal _KeyframeRequest_default_instance_;
class QualityReport;
struct QualityReportDefaultTypeInternal;
extern QualityReportDefaultTypeInternal _QualityReport_default_instance_;
class RemovePublisherReq;
struct RemovePublisherReqDefaultTypeInternal;
extern RemovePublisherReqDefaultTypeInternal _RemovePublisherReq_default_instance_;
class RemovePublisherRsp;
struct RemovePublisherRspDefaultTypeInternal;
extern RemovePublisherRspDefaultTypeInternal _RemovePublisherRsp_default_instance_;
}  // namespace sfu_rpc
PROTOBUF_NAMESPACE_OPEN
template<> ::sfu_rpc::AddPublisherReq* Arena::CreateMaybeMessage<::sfu_rpc::AddPublisherReq>(Arena*);
template<> ::sfu_rpc::AddPublisherRsp* Arena::CreateMaybeMessage<::sfu_rpc::AddPublisherRsp>(Arena*);
template<> ::sfu_rpc::CreateRoomReq* Arena::CreateMaybeMessage<::sfu_rpc::CreateRoomReq>(Arena*);
template<> ::sfu_rpc::CreateRoomRsp* Arena::CreateMaybeMessage<::sfu_rpc::CreateRoomRsp>(Arena*);
template<> ::sfu_rpc::DestroyRoomReq* Arena::CreateMaybeMessage<::sfu_rpc::DestroyRoomReq>(Arena*);
template<> ::sfu_rpc::DestroyRoomRsp* Arena::CreateMaybeMessage<::sfu_rpc::DestroyRoomRsp>(Arena*);
template<> ::sfu_rpc::KeyframeRequest* Arena::CreateMaybeMessage<::sfu_rpc::KeyframeRequest>(Arena*);
template<> ::sfu_rpc::QualityReport* Arena::CreateMaybeMessage<::sfu_rpc::QualityReport>(Arena*);
template<> ::sfu_rpc::RemovePublisherReq* Arena::CreateMaybeMessage<::sfu_rpc::RemovePublisherReq>(Arena*);
template<> ::sfu_rpc::RemovePublisherRsp* Arena::CreateMaybeMessage<::sfu_rpc::RemovePublisherRsp>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace sfu_rpc {

// ===================================================================

class CreateRoomReq final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:sfu_rpc.CreateRoomReq) */ {
 public:
  inline CreateRoomReq() : CreateRoomReq(nullptr) {}
  ~CreateRoomReq() override;
  explicit constexpr CreateRoomReq(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  CreateRoomReq(const CreateRoomReq& from);
  CreateRoomReq(CreateRoomReq&& from) noexcept
    : CreateRoomReq() {
    *this = ::std::move(from);
  }

  inline CreateRoomReq& operator=(const CreateRoomReq& from) {
    CopyFrom(from);
    return *this;
  }
  inline CreateRoomReq& operator=(CreateRoomReq&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const CreateRoomReq& default_instance() {
    return *internal_default_instance();
  }
  static inline const CreateRoomReq* internal_default_instance() {
    return reinterpret_cast<const CreateRoomReq*>(
               &_CreateRoomReq_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(CreateRoomReq& a, CreateRoomReq& b) {
    a.Swap(&b);
  }
  inline void Swap(CreateRoomReq* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(CreateRoomReq* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  CreateRoomReq* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<CreateRoomReq>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const CreateRoomReq& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom(const CreateRoomReq& from);
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to, const ::PROTOBUF_NAMESPACE_ID::Message& from);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(CreateRoomReq* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "sfu_rpc.CreateRoomReq";
  }
  protected:
  explicit CreateRoomReq(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kMeetingIdFieldNumber = 1,
    kMaxPublishersFieldNumber = 2,
  };
  // string meeting_id = 1;
  void clear_meeting_id();
  const std::string& meeting_id() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_meeting_id(ArgT0&& arg0, ArgT... args);
  std::string* mutable_meeting_id();
  PROTOBUF_NODISCARD std::string* release_meeting_id();
  void set_allocated_meeting_id(std::string* meeting_id);
  private:
  const std::string& _internal_meeting_id() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_meeting_id(const std::string& value);
  std::string* _internal_mutable_meeting_id();
  public:

  // int32 max_publishers = 2;
  void clear_max_publishers();
  int32_t max_publishers() const;
  void set_max_publishers(int32_t value);
  private:
  int32_t _internal_max_publishers() const;
  void _internal_set_max_publishers(int32_t value);
  public:

  // @@protoc_insertion_point(class_scope:sfu_rpc.CreateRoomReq)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr meeting_id_;
  int32_t max_publishers_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_sfu_5frpc_2eproto;
};
// -------------------------------------------------------------------

class CreateRoomRsp final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:sfu_rpc.CreateRoomRsp) */ {
 public:
  inline CreateRoomRsp() : CreateRoomRsp(nullptr) {}
  ~CreateRoomRsp() override;
  explicit constexpr CreateRoomRsp(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  CreateRoomRsp(const CreateRoomRsp& from);
  CreateRoomRsp(CreateRoomRsp&& from) noexcept
    : CreateRoomRsp() {
    *this = ::std::move(from);
  }

  inline CreateRoomRsp& operator=(const CreateRoomRsp& from) {
    CopyFrom(from);
    return *this;
  }
  inline CreateRoomRsp& operator=(CreateRoomRsp&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const CreateRoomRsp& default_instance() {
    return *internal_default_instance();
  }
  static inline const CreateRoomRsp* internal_default_instance() {
    return reinterpret_cast<const CreateRoomRsp*>(
               &_CreateRoomRsp_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(CreateRoomRsp& a, CreateRoomRsp& b) {
    a.Swap(&b);
  }
  inline void Swap(CreateRoomRsp* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(CreateRoomRsp* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  CreateRoomRsp* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<CreateRoomRsp>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const CreateRoomRsp& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom(const CreateRoomRsp& from);
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to, const ::PROTOBUF_NAMESPACE_ID::Message& from);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(CreateRoomRsp* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "sfu_rpc.CreateRoomRsp";
  }
  protected:
  explicit CreateRoomRsp(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kSfuAddressFieldNumber = 2,
    kSuccessFieldNumber = 1,
  };
  // string sfu_address = 2;
  void clear_sfu_address();
  const std::string& sfu_address() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_sfu_address(ArgT0&& arg0, ArgT... args);
  std::string* mutable_sfu_address();
  PROTOBUF_NODISCARD std::string* release_sfu_address();
  void set_allocated_sfu_address(std::string* sfu_address);
  private:
  const std::string& _internal_sfu_address() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_sfu_address(const std::string& value);
  std::string* _internal_mutable_sfu_address();
  public:

  // bool success = 1;
  void clear_success();
  bool success() const;
  void set_success(bool value);
  private:
  bool _internal_success() const;
  void _internal_set_success(bool value);
  public:

  // @@protoc_insertion_point(class_scope:sfu_rpc.CreateRoomRsp)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr sfu_address_;
  bool success_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_sfu_5frpc_2eproto;
};
// -------------------------------------------------------------------

class DestroyRoomReq final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:sfu_rpc.DestroyRoomReq) */ {
 public:
  inline DestroyRoomReq() : DestroyRoomReq(nullptr) {}
  ~DestroyRoomReq() override;
  explicit constexpr DestroyRoomReq(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  DestroyRoomReq(const DestroyRoomReq& from);
  DestroyRoomReq(DestroyRoomReq&& from) noexcept
    : DestroyRoomReq() {
    *this = ::std::move(from);
  }

  inline DestroyRoomReq& operator=(const DestroyRoomReq& from) {
    CopyFrom(from);
    return *this;
  }
  inline DestroyRoomReq& operator=(DestroyRoomReq&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const DestroyRoomReq& default_instance() {
    return *internal_default_instance();
  }
  static inline const DestroyRoomReq* internal_default_instance() {
    return reinterpret_cast<const DestroyRoomReq*>(
               &_DestroyRoomReq_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(DestroyRoomReq& a, DestroyRoomReq& b) {
    a.Swap(&b);
  }
  inline void Swap(DestroyRoomReq* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(DestroyRoomReq* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  DestroyRoomReq* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<DestroyRoomReq>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const DestroyRoomReq& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom(const DestroyRoomReq& from);
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to, const ::PROTOBUF_NAMESPACE_ID::Message& from);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(DestroyRoomReq* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "sfu_rpc.DestroyRoomReq";
  }
  protected:
  explicit DestroyRoomReq(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kMeetingIdFieldNumber = 1,
  };
  // string meeting_id = 1;
  void clear_meeting_id();
  const std::string& meeting_id() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_meeting_id(ArgT0&& arg0, ArgT... args);
  std::string* mutable_meeting_id();
  PROTOBUF_NODISCARD std::string* release_meeting_id();
  void set_allocated_meeting_id(std::string* meeting_id);
  private:
  const std::string& _internal_meeting_id() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_meeting_id(const std::string& value);
  std::string* _internal_mutable_meeting_id();
  public:

  // @@protoc_insertion_point(class_scope:sfu_rpc.DestroyRoomReq)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr meeting_id_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_sfu_5frpc_2eproto;
};
// -------------------------------------------------------------------

class DestroyRoomRsp final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:sfu_rpc.DestroyRoomRsp) */ {
 public:
  inline DestroyRoomRsp() : DestroyRoomRsp(nullptr) {}
  ~DestroyRoomRsp() override;
  explicit constexpr DestroyRoomRsp(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  DestroyRoomRsp(const DestroyRoomRsp& from);
  DestroyRoomRsp(DestroyRoomRsp&& from) noexcept
    : DestroyRoomRsp() {
    *this = ::std::move(from);
  }

  inline DestroyRoomRsp& operator=(const DestroyRoomRsp& from) {
    CopyFrom(from);
    return *this;
  }
  inline DestroyRoomRsp& operator=(DestroyRoomRsp&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const DestroyRoomRsp& default_instance() {
    return *internal_default_instance();
  }
  static inline const DestroyRoomRsp* internal_default_instance() {
    return reinterpret_cast<const DestroyRoomRsp*>(
               &_DestroyRoomRsp_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  friend void swap(DestroyRoomRsp& a, DestroyRoomRsp& b) {
    a.Swap(&b);
  }
  inline void Swap(DestroyRoomRsp* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(DestroyRoomRsp* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  DestroyRoomRsp* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<DestroyRoomRsp>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const DestroyRoomRsp& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom(const DestroyRoomRsp& from);
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to, const ::PROTOBUF_NAMESPACE_ID::Message& from);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(DestroyRoomRsp* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "sfu_rpc.DestroyRoomRsp";
  }
  protected:
  explicit DestroyRoomRsp(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kSuccessFieldNumber = 1,
  };
  // bool success = 1;
  void clear_success();
  bool success() const;
  void set_success(bool value);
  private:
  bool _internal_success() const;
  void _internal_set_success(bool value);
  public:

  // @@protoc_insertion_point(class_scope:sfu_rpc.DestroyRoomRsp)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  bool success_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_sfu_5frpc_2eproto;
};
// -------------------------------------------------------------------

class AddPublisherReq final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:sfu_rpc.AddPublisherReq) */ {
 public:
  inline AddPublisherReq() : AddPublisherReq(nullptr) {}
  ~AddPublisherReq() override;
  explicit constexpr AddPublisherReq(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  AddPublisherReq(const AddPublisherReq& from);
  AddPublisherReq(AddPublisherReq&& from) noexcept
    : AddPublisherReq() {
    *this = ::std::move(from);
  }

  inline AddPublisherReq& operator=(const AddPublisherReq& from) {
    CopyFrom(from);
    return *this;
  }
  inline AddPublisherReq& operator=(AddPublisherReq&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const AddPublisherReq& default_instance() {
    return *internal_default_instance();
  }
  static inline const AddPublisherReq* internal_default_instance() {
    return reinterpret_cast<const AddPublisherReq*>(
               &_AddPublisherReq_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    4;

  friend void swap(AddPublisherReq& a, AddPublisherReq& b) {
    a.Swap(&b);
  }
  inline void Swap(AddPublisherReq* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(AddPublisherReq* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  AddPublisherReq* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<AddPublisherReq>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const AddPublisherReq& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom(const AddPublisherReq& from);
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to, const ::PROTOBUF_NAMESPACE_ID::Message& from);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(AddPublisherReq* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "sfu_rpc.AddPublisherReq";
  }
  protected:
  explicit AddPublisherReq(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kMeetingIdFieldNumber = 1,
    kUserIdFieldNumber = 2,
    kAudioSsrcFieldNumber = 3,
    kVideoSsrcFieldNumber = 4,
  };
  // string meeting_id = 1;
  void clear_meeting_id();
  const std::string& meeting_id() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_meeting_id(ArgT0&& arg0, ArgT... args);
  std::string* mutable_meeting_id();
  PROTOBUF_NODISCARD std::string* release_meeting_id();
  void set_allocated_meeting_id(std::string* meeting_id);
  private:
  const std::string& _internal_meeting_id() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_meeting_id(const std::string& value);
  std::string* _internal_mutable_meeting_id();
  public:

  // string user_id = 2;
  void clear_user_id();
  const std::string& user_id() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_user_id(ArgT0&& arg0, ArgT... args);
  std::string* mutable_user_id();
  PROTOBUF_NODISCARD std::string* release_user_id();
  void set_allocated_user_id(std::string* user_id);
  private:
  const std::string& _internal_user_id() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_user_id(const std::string& value);
  std::string* _internal_mutable_user_id();
  public:

  // uint32 audio_ssrc = 3;
  void clear_audio_ssrc();
  uint32_t audio_ssrc() const;
  void set_audio_ssrc(uint32_t value);
  private:
  uint32_t _internal_audio_ssrc() const;
  void _internal_set_audio_ssrc(uint32_t value);
  public:

  // uint32 video_ssrc = 4;
  void clear_video_ssrc();
  uint32_t video_ssrc() const;
  void set_video_ssrc(uint32_t value);
  private:
  uint32_t _internal_video_ssrc() const;
  void _internal_set_video_ssrc(uint32_t value);
  public:

  // @@protoc_insertion_point(class_scope:sfu_rpc.AddPublisherReq)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr meeting_id_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr user_id_;
  uint32_t audio_ssrc_;
  uint32_t video_ssrc_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_sfu_5frpc_2eproto;
};
// -------------------------------------------------------------------

class AddPublisherRsp final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:sfu_rpc.AddPublisherRsp) */ {
 public:
  inline AddPublisherRsp() : AddPublisherRsp(nullptr) {}
  ~AddPublisherRsp() override;
  explicit constexpr AddPublisherRsp(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  AddPublisherRsp(const AddPublisherRsp& from);
  AddPublisherRsp(AddPublisherRsp&& from) noexcept
    : AddPublisherRsp() {
    *this = ::std::move(from);
  }

  inline AddPublisherRsp& operator=(const AddPublisherRsp& from) {
    CopyFrom(from);
    return *this;
  }
  inline AddPublisherRsp& operator=(AddPublisherRsp&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const AddPublisherRsp& default_instance() {
    return *internal_default_instance();
  }
  static inline const AddPublisherRsp* internal_default_instance() {
    return reinterpret_cast<const AddPublisherRsp*>(
               &_AddPublisherRsp_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    5;

  friend void swap(AddPublisherRsp& a, AddPublisherRsp& b) {
    a.Swap(&b);
  }
  inline void Swap(AddPublisherRsp* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(AddPublisherRsp* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  AddPublisherRsp* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<AddPublisherRsp>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const AddPublisherRsp& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom(const AddPublisherRsp& from);
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to, const ::PROTOBUF_NAMESPACE_ID::Message& from);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(AddPublisherRsp* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "sfu_rpc.AddPublisherRsp";
  }
  protected:
  explicit AddPublisherRsp(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kSuccessFieldNumber = 1,
    kUdpPortFieldNumber = 2,
  };
  // bool success = 1;
  void clear_success();
  bool success() const;
  void set_success(bool value);
  private:
  bool _internal_success() const;
  void _internal_set_success(bool value);
  public:

  // uint32 udp_port = 2;
  void clear_udp_port();
  uint32_t udp_port() const;
  void set_udp_port(uint32_t value);
  private:
  uint32_t _internal_udp_port() const;
  void _internal_set_udp_port(uint32_t value);
  public:

  // @@protoc_insertion_point(class_scope:sfu_rpc.AddPublisherRsp)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  bool success_;
  uint32_t udp_port_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_sfu_5frpc_2eproto;
};
// -------------------------------------------------------------------

class RemovePublisherReq final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:sfu_rpc.RemovePublisherReq) */ {
 public:
  inline RemovePublisherReq() : RemovePublisherReq(nullptr) {}
  ~RemovePublisherReq() override;
  explicit constexpr RemovePublisherReq(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  RemovePublisherReq(const RemovePublisherReq& from);
  RemovePublisherReq(RemovePublisherReq&& from) noexcept
    : RemovePublisherReq() {
    *this = ::std::move(from);
  }

  inline RemovePublisherReq& operator=(const RemovePublisherReq& from) {
    CopyFrom(from);
    return *this;
  }
  inline RemovePublisherReq& operator=(RemovePublisherReq&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const RemovePublisherReq& default_instance() {
    return *internal_default_instance();
  }
  static inline const RemovePublisherReq* internal_default_instance() {
    return reinterpret_cast<const RemovePublisherReq*>(
               &_RemovePublisherReq_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    6;

  friend void swap(RemovePublisherReq& a, RemovePublisherReq& b) {
    a.Swap(&b);
  }
  inline void Swap(RemovePublisherReq* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(RemovePublisherReq* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  RemovePublisherReq* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<RemovePublisherReq>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const RemovePublisherReq& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom(const RemovePublisherReq& from);
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to, const ::PROTOBUF_NAMESPACE_ID::Message& from);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(RemovePublisherReq* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "sfu_rpc.RemovePublisherReq";
  }
  protected:
  explicit RemovePublisherReq(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kMeetingIdFieldNumber = 1,
    kUserIdFieldNumber = 2,
  };
  // string meeting_id = 1;
  void clear_meeting_id();
  const std::string& meeting_id() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_meeting_id(ArgT0&& arg0, ArgT... args);
  std::string* mutable_meeting_id();
  PROTOBUF_NODISCARD std::string* release_meeting_id();
  void set_allocated_meeting_id(std::string* meeting_id);
  private:
  const std::string& _internal_meeting_id() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_meeting_id(const std::string& value);
  std::string* _internal_mutable_meeting_id();
  public:

  // string user_id = 2;
  void clear_user_id();
  const std::string& user_id() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_user_id(ArgT0&& arg0, ArgT... args);
  std::string* mutable_user_id();
  PROTOBUF_NODISCARD std::string* release_user_id();
  void set_allocated_user_id(std::string* user_id);
  private:
  const std::string& _internal_user_id() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_user_id(const std::string& value);
  std::string* _internal_mutable_user_id();
  public:

  // @@protoc_insertion_point(class_scope:sfu_rpc.RemovePublisherReq)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr meeting_id_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr user_id_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_sfu_5frpc_2eproto;
};
// -------------------------------------------------------------------

class RemovePublisherRsp final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:sfu_rpc.RemovePublisherRsp) */ {
 public:
  inline RemovePublisherRsp() : RemovePublisherRsp(nullptr) {}
  ~RemovePublisherRsp() override;
  explicit constexpr RemovePublisherRsp(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  RemovePublisherRsp(const RemovePublisherRsp& from);
  RemovePublisherRsp(RemovePublisherRsp&& from) noexcept
    : RemovePublisherRsp() {
    *this = ::std::move(from);
  }

  inline RemovePublisherRsp& operator=(const RemovePublisherRsp& from) {
    CopyFrom(from);
    return *this;
  }
  inline RemovePublisherRsp& operator=(RemovePublisherRsp&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const RemovePublisherRsp& default_instance() {
    return *internal_default_instance();
  }
  static inline const RemovePublisherRsp* internal_default_instance() {
    return reinterpret_cast<const RemovePublisherRsp*>(
               &_RemovePublisherRsp_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    7;

  friend void swap(RemovePublisherRsp& a, RemovePublisherRsp& b) {
    a.Swap(&b);
  }
  inline void Swap(RemovePublisherRsp* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(RemovePublisherRsp* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  RemovePublisherRsp* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<RemovePublisherRsp>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const RemovePublisherRsp& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom(const RemovePublisherRsp& from);
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to, const ::PROTOBUF_NAMESPACE_ID::Message& from);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(RemovePublisherRsp* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "sfu_rpc.RemovePublisherRsp";
  }
  protected:
  explicit RemovePublisherRsp(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kSuccessFieldNumber = 1,
  };
  // bool success = 1;
  void clear_success();
  bool success() const;
  void set_success(bool value);
  private:
  bool _internal_success() const;
  void _internal_set_success(bool value);
  public:

  // @@protoc_insertion_point(class_scope:sfu_rpc.RemovePublisherRsp)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  bool success_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_sfu_5frpc_2eproto;
};
// -------------------------------------------------------------------

class QualityReport final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:sfu_rpc.QualityReport) */ {
 public:
  inline QualityReport() : QualityReport(nullptr) {}
  ~QualityReport() override;
  explicit constexpr QualityReport(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  QualityReport(const QualityReport& from);
  QualityReport(QualityReport&& from) noexcept
    : QualityReport() {
    *this = ::std::move(from);
  }

  inline QualityReport& operator=(const QualityReport& from) {
    CopyFrom(from);
    return *this;
  }
  inline QualityReport& operator=(QualityReport&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const QualityReport& default_instance() {
    return *internal_default_instance();
  }
  static inline const QualityReport* internal_default_instance() {
    return reinterpret_cast<const QualityReport*>(
               &_QualityReport_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    8;

  friend void swap(QualityReport& a, QualityReport& b) {
    a.Swap(&b);
  }
  inline void Swap(QualityReport* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(QualityReport* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  QualityReport* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<QualityReport>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const QualityReport& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom(const QualityReport& from);
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to, const ::PROTOBUF_NAMESPACE_ID::Message& from);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(QualityReport* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "sfu_rpc.QualityReport";
  }
  protected:
  explicit QualityReport(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kMeetingIdFieldNumber = 1,
    kUserIdFieldNumber = 2,
    kPacketLossFieldNumber = 3,
    kRttMsFieldNumber = 4,
    kJitterMsFieldNumber = 5,
    kBitrateKbpsFieldNumber = 6,
  };
  // string meeting_id = 1;
  void clear_meeting_id();
  const std::string& meeting_id() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_meeting_id(ArgT0&& arg0, ArgT... args);
  std::string* mutable_meeting_id();
  PROTOBUF_NODISCARD std::string* release_meeting_id();
  void set_allocated_meeting_id(std::string* meeting_id);
  private:
  const std::string& _internal_meeting_id() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_meeting_id(const std::string& value);
  std::string* _internal_mutable_meeting_id();
  public:

  // string user_id = 2;
  void clear_user_id();
  const std::string& user_id() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_user_id(ArgT0&& arg0, ArgT... args);
  std::string* mutable_user_id();
  PROTOBUF_NODISCARD std::string* release_user_id();
  void set_allocated_user_id(std::string* user_id);
  private:
  const std::string& _internal_user_id() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_user_id(const std::string& value);
  std::string* _internal_mutable_user_id();
  public:

  // float packet_loss = 3;
  void clear_packet_loss();
  float packet_loss() const;
  void set_packet_loss(float value);
  private:
  float _internal_packet_loss() const;
  void _internal_set_packet_loss(float value);
  public:

  // uint32 rtt_ms = 4;
  void clear_rtt_ms();
  uint32_t rtt_ms() const;
  void set_rtt_ms(uint32_t value);
  private:
  uint32_t _internal_rtt_ms() const;
  void _internal_set_rtt_ms(uint32_t value);
  public:

  // uint32 jitter_ms = 5;
  void clear_jitter_ms();
  uint32_t jitter_ms() const;
  void set_jitter_ms(uint32_t value);
  private:
  uint32_t _internal_jitter_ms() const;
  void _internal_set_jitter_ms(uint32_t value);
  public:

  // uint32 bitrate_kbps = 6;
  void clear_bitrate_kbps();
  uint32_t bitrate_kbps() const;
  void set_bitrate_kbps(uint32_t value);
  private:
  uint32_t _internal_bitrate_kbps() const;
  void _internal_set_bitrate_kbps(uint32_t value);
  public:

  // @@protoc_insertion_point(class_scope:sfu_rpc.QualityReport)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr meeting_id_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr user_id_;
  float packet_loss_;
  uint32_t rtt_ms_;
  uint32_t jitter_ms_;
  uint32_t bitrate_kbps_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_sfu_5frpc_2eproto;
};
// -------------------------------------------------------------------

class KeyframeRequest final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:sfu_rpc.KeyframeRequest) */ {
 public:
  inline KeyframeRequest() : KeyframeRequest(nullptr) {}
  ~KeyframeRequest() override;
  explicit constexpr KeyframeRequest(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  KeyframeRequest(const KeyframeRequest& from);
  KeyframeRequest(KeyframeRequest&& from) noexcept
    : KeyframeRequest() {
    *this = ::std::move(from);
  }

  inline KeyframeRequest& operator=(const KeyframeRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline KeyframeRequest& operator=(KeyframeRequest&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const KeyframeRequest& default_instance() {
    return *internal_default_instance();
  }
  static inline const KeyframeRequest* internal_default_instance() {
    return reinterpret_cast<const KeyframeRequest*>(
               &_KeyframeRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    9;

  friend void swap(KeyframeRequest& a, KeyframeRequest& b) {
    a.Swap(&b);
  }
  inline void Swap(KeyframeRequest* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(KeyframeRequest* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  KeyframeRequest* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<KeyframeRequest>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const KeyframeRequest& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom(const KeyframeRequest& from);
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to, const ::PROTOBUF_NAMESPACE_ID::Message& from);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(KeyframeRequest* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "sfu_rpc.KeyframeRequest";
  }
  protected:
  explicit KeyframeRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kMeetingIdFieldNumber = 1,
    kUserIdFieldNumber = 2,
  };
  // string meeting_id = 1;
  void clear_meeting_id();
  const std::string& meeting_id() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_meeting_id(ArgT0&& arg0, ArgT... args);
  std::string* mutable_meeting_id();
  PROTOBUF_NODISCARD std::string* release_meeting_id();
  void set_allocated_meeting_id(std::string* meeting_id);
  private:
  const std::string& _internal_meeting_id() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_meeting_id(const std::string& value);
  std::string* _internal_mutable_meeting_id();
  public:

  // string user_id = 2;
  void clear_user_id();
  const std::string& user_id() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_user_id(ArgT0&& arg0, ArgT... args);
  std::string* mutable_user_id();
  PROTOBUF_NODISCARD std::string* release_user_id();
  void set_allocated_user_id(std::string* user_id);
  private:
  const std::string& _internal_user_id() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_user_id(const std::string& value);
  std::string* _internal_mutable_user_id();
  public:

  // @@protoc_insertion_point(class_scope:sfu_rpc.KeyframeRequest)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr meeting_id_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr user_id_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_sfu_5frpc_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// CreateRoomReq

// string meeting_id = 1;
inline void CreateRoomReq::clear_meeting_id() {
  meeting_id_.ClearToEmpty();
}
inline const std::string& CreateRoomReq::meeting_id() const {
  // @@protoc_insertion_point(field_get:sfu_rpc.CreateRoomReq.meeting_id)
  return _internal_meeting_id();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void CreateRoomReq::set_meeting_id(ArgT0&& arg0, ArgT... args) {

 meeting_id_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:sfu_rpc.CreateRoomReq.meeting_id)
}
inline std::string* CreateRoomReq::mutable_meeting_id() {
  std::string* _s = _internal_mutable_meeting_id();
  // @@protoc_insertion_point(field_mutable:sfu_rpc.CreateRoomReq.meeting_id)
  return _s;
}
inline const std::string& CreateRoomReq::_internal_meeting_id() const {
  return meeting_id_.Get();
}
inline void CreateRoomReq::_internal_set_meeting_id(const std::string& value) {

  meeting_id_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArenaForAllocation());
}
inline std::string* CreateRoomReq::_internal_mutable_meeting_id() {

  return meeting_id_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArenaForAllocation());
}
inline std::string* CreateRoomReq::release_meeting_id() {
  // @@protoc_insertion_point(field_release:sfu_rpc.CreateRoomReq.meeting_id)
  return meeting_id_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArenaForAllocation());
}
inline void CreateRoomReq::set_allocated_meeting_id(std::string* meeting_id) {
  if (meeting_id != nullptr) {

  } else {

  }
  meeting_id_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), meeting_id,
      GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (meeting_id_.IsDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited())) {
    meeting_id_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), "", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:sfu_rpc.CreateRoomReq.meeting_id)
}

// int32 max_publishers = 2;
inline void CreateRoomReq::clear_max_publishers() {
  max_publishers_ = 0;
}
inline int32_t CreateRoomReq::_internal_max_publishers() const {
  return max_publishers_;
}
inline int32_t CreateRoomReq::max_publishers() const {
  // @@protoc_insertion_point(field_get:sfu_rpc.CreateRoomReq.max_publishers)
  return _internal_max_publishers();
}
inline void CreateRoomReq::_internal_set_max_publishers(int32_t value) {

  max_publishers_ = value;
}
inline void CreateRoomReq::set_max_publishers(int32_t value) {
  _internal_set_max_publishers(value);
  // @@protoc_insertion_point(field_set:sfu_rpc.CreateRoomReq.max_publishers)
}

// -------------------------------------------------------------------

// CreateRoomRsp

// bool success = 1;
inline void CreateRoomRsp::clear_success() {
  success_ = false;
}
inline bool CreateRoomRsp::_internal_success() const {
  return success_;
}
inline bool CreateRoomRsp::success() const {
  // @@protoc_insertion_point(field_get:sfu_rpc.CreateRoomRsp.success)
  return _internal_success();
}
inline void CreateRoomRsp::_internal_set_success(bool value) {

  success_ = value;
}
inline void CreateRoomRsp::set_success(bool value) {
  _internal_set_success(value);
  // @@protoc_insertion_point(field_set:sfu_rpc.CreateRoomRsp.success)
}

// string sfu_address = 2;
inline void CreateRoomRsp::clear_sfu_address() {
  sfu_address_.ClearToEmpty();
}
inline const std::string& CreateRoomRsp::sfu_address() const {
  // @@protoc_insertion_point(field_get:sfu_rpc.CreateRoomRsp.sfu_address)
  return _internal_sfu_address();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void CreateRoomRsp::set_sfu_address(ArgT0&& arg0, ArgT... args) {

 sfu_address_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:sfu_rpc.CreateRoomRsp.sfu_address)
}
inline std::string* CreateRoomRsp::mutable_sfu_address() {
  std::string* _s = _internal_mutable_sfu_address();
  // @@protoc_insertion_point(field_mutable:sfu_rpc.CreateRoomRsp.sfu_address)
  return _s;
}
inline const std::string& CreateRoomRsp::_internal_sfu_address() const {
  return sfu_address_.Get();
}
inline void CreateRoomRsp::_internal_set_sfu_address(const std::string& value) {

  sfu_address_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArenaForAllocation());
}
inline std::string* CreateRoomRsp::_internal_mutable_sfu_address() {

  return sfu_address_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArenaForAllocation());
}
inline std::string* CreateRoomRsp::release_sfu_address() {
  // @@protoc_insertion_point(field_release:sfu_rpc.CreateRoomRsp.sfu_address)
  return sfu_address_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArenaForAllocation());
}
inline void CreateRoomRsp::set_allocated_sfu_address(std::string* sfu_address) {
  if (sfu_address != nullptr) {

  } else {

  }
  sfu_address_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), sfu_address,
      GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (sfu_address_.IsDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited())) {
    sfu_address_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), "", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:sfu_rpc.CreateRoomRsp.sfu_address)
}

// -------------------------------------------------------------------

// DestroyRoomReq

// string meeting_id = 1;
inline void DestroyRoomReq::clear_meeting_id() {
  meeting_id_.ClearToEmpty();
}
inline const std::string& DestroyRoomReq::meeting_id() const {
  // @@protoc_insertion_point(field_get:sfu_rpc.DestroyRoomReq.meeting_id)
  return _internal_meeting_id();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void DestroyRoomReq::set_meeting_id(ArgT0&& arg0, ArgT... args) {

 meeting_id_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:sfu_rpc.DestroyRoomReq.meeting_id)
}
inline std::string* DestroyRoomReq::mutable_meeting_id() {
  std::string* _s = _internal_mutable_meeting_id();
  // @@protoc_insertion_point(field_mutable:sfu_rpc.DestroyRoomReq.meeting_id)
  return _s;
}
inline const std::string& DestroyRoomReq::_internal_meeting_id() const {
  return meeting_id_.Get();
}
inline void DestroyRoomReq::_internal_set_meeting_id(const std::string& value) {

  meeting_id_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArenaForAllocation());
}
inline std::string* DestroyRoomReq::_internal_mutable_meeting_id() {

  return meeting_id_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArenaForAllocation());
}
inline std::string* DestroyRoomReq::release_meeting_id() {
  // @@protoc_insertion_point(field_release:sfu_rpc.DestroyRoomReq.meeting_id)
  return meeting_id_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArenaForAllocation());
}
inline void DestroyRoomReq::set_allocated_meeting_id(std::string* meeting_id) {
  if (meeting_id != nullptr) {

  } else {

  }
  meeting_id_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), meeting_id,
      GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (meeting_id_.IsDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited())) {
    meeting_id_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), "", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:sfu_rpc.DestroyRoomReq.meeting_id)
}

// -------------------------------------------------------------------

// DestroyRoomRsp

// bool success = 1;
inline void DestroyRoomRsp::clear_success() {
  success_ = false;
}
inline bool DestroyRoomRsp::_internal_success() const {
  return success_;
}
inline bool DestroyRoomRsp::success() const {
  // @@protoc_insertion_point(field_get:sfu_rpc.DestroyRoomRsp.success)
  return _internal_success();
}
inline void DestroyRoomRsp::_internal_set_success(bool value) {

  success_ = value;
}
inline void DestroyRoomRsp::set_success(bool value) {
  _internal_set_success(value);
  // @@protoc_insertion_point(field_set:sfu_rpc.DestroyRoomRsp.success)
}

// -------------------------------------------------------------------

// AddPublisherReq

// string meeting_id = 1;
inline void AddPublisherReq::clear_meeting_id() {
  meeting_id_.ClearToEmpty();
}
inline const std::string& AddPublisherReq::meeting_id() const {
  // @@protoc_insertion_point(field_get:sfu_rpc.AddPublisherReq.meeting_id)
  return _internal_meeting_id();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void AddPublisherReq::set_meeting_id(ArgT0&& arg0, ArgT... args) {

 meeting_id_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:sfu_rpc.AddPublisherReq.meeting_id)
}
inline std::string* AddPublisherReq::mutable_meeting_id() {
  std::string* _s = _internal_mutable_meeting_id();
  // @@protoc_insertion_point(field_mutable:sfu_rpc.AddPublisherReq.meeting_id)
  return _s;
}
inline const std::string& AddPublisherReq::_internal_meeting_id() const {
  return meeting_id_.Get();
}
inline void AddPublisherReq::_internal_set_meeting_id(const std::string& value) {

  meeting_id_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArenaForAllocation());
}
inline std::string* AddPublisherReq::_internal_mutable_meeting_id() {

  return meeting_id_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArenaForAllocation());
}
inline std::string* AddPublisherReq::release_meeting_id() {
  // @@protoc_insertion_point(field_release:sfu_rpc.AddPublisherReq.meeting_id)
  return meeting_id_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArenaForAllocation());
}
inline void AddPublisherReq::set_allocated_meeting_id(std::string* meeting_id) {
  if (meeting_id != nullptr) {

  } else {

  }
  meeting_id_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), meeting_id,
      GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (meeting_id_.IsDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited())) {
    meeting_id_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), "", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:sfu_rpc.AddPublisherReq.meeting_id)
}

// string user_id = 2;
inline void AddPublisherReq::clear_user_id() {
  user_id_.ClearToEmpty();
}
inline const std::string& AddPublisherReq::user_id() const {
  // @@protoc_insertion_point(field_get:sfu_rpc.AddPublisherReq.user_id)
  return _internal_user_id();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void AddPublisherReq::set_user_id(ArgT0&& arg0, ArgT... args) {

 user_id_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:sfu_rpc.AddPublisherReq.user_id)
}
inline std::string* AddPublisherReq::mutable_user_id() {
  std::string* _s = _internal_mutable_user_id();
  // @@protoc_insertion_point(field_mutable:sfu_rpc.AddPublisherReq.user_id)
  return _s;
}
inline const std::string& AddPublisherReq::_internal_user_id() const {
  return user_id_.Get();
}
inline void AddPublisherReq::_internal_set_user_id(const std::string& value) {

  user_id_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArenaForAllocation());
}
inline std::string* AddPublisherReq::_internal_mutable_user_id() {

  return user_id_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArenaForAllocation());
}
inline std::string* AddPublisherReq::release_user_id() {
  // @@protoc_insertion_point(field_release:sfu_rpc.AddPublisherReq.user_id)
  return user_id_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArenaForAllocation());
}
inline void AddPublisherReq::set_allocated_user_id(std::string* user_id) {
  if (user_id != nullptr) {

  } else {

  }
  user_id_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), user_id,
      GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (user_id_.IsDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited())) {
    user_id_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), "", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:sfu_rpc.AddPublisherReq.user_id)
}

// uint32 audio_ssrc = 3;
inline void AddPublisherReq::clear_audio_ssrc() {
  audio_ssrc_ = 0u;
}
inline uint32_t AddPublisherReq::_internal_audio_ssrc() const {
  return audio_ssrc_;
}
inline uint32_t AddPublisherReq::audio_ssrc() const {
  // @@protoc_insertion_point(field_get:sfu_rpc.AddPublisherReq.audio_ssrc)
  return _internal_audio_ssrc();
}
inline void AddPublisherReq::_internal_set_audio_ssrc(uint32_t value) {

  audio_ssrc_ = value;
}
inline void AddPublisherReq::set_audio_ssrc(uint32_t value) {
  _internal_set_audio_ssrc(value);
  // @@protoc_insertion_point(field_set:sfu_rpc.AddPublisherReq.audio_ssrc)
}

// uint32 video_ssrc = 4;
inline void AddPublisherReq::clear_video_ssrc() {
  video_ssrc_ = 0u;
}
inline uint32_t AddPublisherReq::_internal_video_ssrc() const {
  return video_ssrc_;
}
inline uint32_t AddPublisherReq::video_ssrc() const {
  // @@protoc_insertion_point(field_get:sfu_rpc.AddPublisherReq.video_ssrc)
  return _internal_video_ssrc();
}
inline void AddPublisherReq::_internal_set_video_ssrc(uint32_t value) {

  video_ssrc_ = value;
}
inline void AddPublisherReq::set_video_ssrc(uint32_t value) {
  _internal_set_video_ssrc(value);
  // @@protoc_insertion_point(field_set:sfu_rpc.AddPublisherReq.video_ssrc)
}

// -------------------------------------------------------------------

// AddPublisherRsp

// bool success = 1;
inline void AddPublisherRsp::clear_success() {
  success_ = false;
}
inline bool AddPublisherRsp::_internal_success() const {
  return success_;
}
inline bool AddPublisherRsp::success() const {
  // @@protoc_insertion_point(field_get:sfu_rpc.AddPublisherRsp.success)
  return _internal_success();
}
inline void AddPublisherRsp::_internal_set_success(bool value) {

  success_ = value;
}
inline void AddPublisherRsp::set_success(bool value) {
  _internal_set_success(value);
  // @@protoc_insertion_point(field_set:sfu_rpc.AddPublisherRsp.success)
}

// uint32 udp_port = 2;
inline void AddPublisherRsp::clear_udp_port() {
  udp_port_ = 0u;
}
inline uint32_t AddPublisherRsp::_internal_udp_port() const {
  return udp_port_;
}
inline uint32_t AddPublisherRsp::udp_port() const {
  // @@protoc_insertion_point(field_get:sfu_rpc.AddPublisherRsp.udp_port)
  return _internal_udp_port();
}
inline void AddPublisherRsp::_internal_set_udp_port(uint32_t value) {

  udp_port_ = value;
}
inline void AddPublisherRsp::set_udp_port(uint32_t value) {
  _internal_set_udp_port(value);
  // @@protoc_insertion_point(field_set:sfu_rpc.AddPublisherRsp.udp_port)
}

// -------------------------------------------------------------------

// RemovePublisherReq

// string meeting_id = 1;
inline void RemovePublisherReq::clear_meeting_id() {
  meeting_id_.ClearToEmpty();
}
inline const std::string& RemovePublisherReq::meeting_id() const {
  // @@protoc_insertion_point(field_get:sfu_rpc.RemovePublisherReq.meeting_id)
  return _internal_meeting_id();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void RemovePublisherReq::set_meeting_id(ArgT0&& arg0, ArgT... args) {

 meeting_id_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:sfu_rpc.RemovePublisherReq.meeting_id)
}
inline std::string* RemovePublisherReq::mutable_meeting_id() {
  std::string* _s = _internal_mutable_meeting_id();
  // @@protoc_insertion_point(field_mutable:sfu_rpc.RemovePublisherReq.meeting_id)
  return _s;
}
inline const std::string& RemovePublisherReq::_internal_meeting_id() const {
  return meeting_id_.Get();
}
inline void RemovePublisherReq::_internal_set_meeting_id(const std::string& value) {

  meeting_id_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArenaForAllocation());
}
inline std::string* RemovePublisherReq::_internal_mutable_meeting_id() {

  return meeting_id_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArenaForAllocation());
}
inline std::string* RemovePublisherReq::release_meeting_id() {
  // @@protoc_insertion_point(field_release:sfu_rpc.RemovePublisherReq.meeting_id)
  return meeting_id_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArenaForAllocation());
}
inline void RemovePublisherReq::set_allocated_meeting_id(std::string* meeting_id) {
  if (meeting_id != nullptr) {

  } else {

  }
  meeting_id_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), meeting_id,
      GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (meeting_id_.IsDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited())) {
    meeting_id_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), "", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:sfu_rpc.RemovePublisherReq.meeting_id)
}

// string user_id = 2;
inline void RemovePublisherReq::clear_user_id() {
  user_id_.ClearToEmpty();
}
inline const std::string& RemovePublisherReq::user_id() const {
  // @@protoc_insertion_point(field_get:sfu_rpc.RemovePublisherReq.user_id)
  return _internal_user_id();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void RemovePublisherReq::set_user_id(ArgT0&& arg0, ArgT... args) {

 user_id_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:sfu_rpc.RemovePublisherReq.user_id)
}
inline std::string* RemovePublisherReq::mutable_user_id() {
  std::string* _s = _internal_mutable_user_id();
  // @@protoc_insertion_point(field_mutable:sfu_rpc.RemovePublisherReq.user_id)
  return _s;
}
inline const std::string& RemovePublisherReq::_internal_user_id() const {
  return user_id_.Get();
}
inline void RemovePublisherReq::_internal_set_user_id(const std::string& value) {

  user_id_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArenaForAllocation());
}
inline std::string* RemovePublisherReq::_internal_mutable_user_id() {

  return user_id_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArenaForAllocation());
}
inline std::string* RemovePublisherReq::release_user_id() {
  // @@protoc_insertion_point(field_release:sfu_rpc.RemovePublisherReq.user_id)
  return user_id_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArenaForAllocation());
}
inline void RemovePublisherReq::set_allocated_user_id(std::string* user_id) {
  if (user_id != nullptr) {

  } else {

  }
  user_id_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), user_id,
      GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (user_id_.IsDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited())) {
    user_id_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), "", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:sfu_rpc.RemovePublisherReq.user_id)
}

// -------------------------------------------------------------------

// RemovePublisherRsp

// bool success = 1;
inline void RemovePublisherRsp::clear_success() {
  success_ = false;
}
inline bool RemovePublisherRsp::_internal_success() const {
  return success_;
}
inline bool RemovePublisherRsp::success() const {
  // @@protoc_insertion_point(field_get:sfu_rpc.RemovePublisherRsp.success)
  return _internal_success();
}
inline void RemovePublisherRsp::_internal_set_success(bool value) {

  success_ = value;
}
inline void RemovePublisherRsp::set_success(bool value) {
  _internal_set_success(value);
  // @@protoc_insertion_point(field_set:sfu_rpc.RemovePublisherRsp.success)
}

// -------------------------------------------------------------------

// QualityReport

// string meeting_id = 1;
inline void QualityReport::clear_meeting_id() {
  meeting_id_.ClearToEmpty();
}
inline const std::string& QualityReport::meeting_id() const {
  // @@protoc_insertion_point(field_get:sfu_rpc.QualityReport.meeting_id)
  return _internal_meeting_id();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void QualityReport::set_meeting_id(ArgT0&& arg0, ArgT... args) {

 meeting_id_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:sfu_rpc.QualityReport.meeting_id)
}
inline std::string* QualityReport::mutable_meeting_id() {
  std::string* _s = _internal_mutable_meeting_id();
  // @@protoc_insertion_point(field_mutable:sfu_rpc.QualityReport.meeting_id)
  return _s;
}
inline const std::string& QualityReport::_internal_meeting_id() const {
  return meeting_id_.Get();
}
inline void QualityReport::_internal_set_meeting_id(const std::string& value) {

  meeting_id_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArenaForAllocation());
}
inline std::string* QualityReport::_internal_mutable_meeting_id() {

  return meeting_id_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArenaForAllocation());
}
inline std::string* QualityReport::release_meeting_id() {
  // @@protoc_insertion_point(field_release:sfu_rpc.QualityReport.meeting_id)
  return meeting_id_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArenaForAllocation());
}
inline void QualityReport::set_allocated_meeting_id(std::string* meeting_id) {
  if (meeting_id != nullptr) {

  } else {

  }
  meeting_id_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), meeting_id,
      GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (meeting_id_.IsDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited())) {
    meeting_id_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), "", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:sfu_rpc.QualityReport.meeting_id)
}

// string user_id = 2;
inline void QualityReport::clear_user_id() {
  user_id_.ClearToEmpty();
}
inline const std::string& QualityReport::user_id() const {
  // @@protoc_insertion_point(field_get:sfu_rpc.QualityReport.user_id)
  return _internal_user_id();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void QualityReport::set_user_id(ArgT0&& arg0, ArgT... args) {

 user_id_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:sfu_rpc.QualityReport.user_id)
}
inline std::string* QualityReport::mutable_user_id() {
  std::string* _s = _internal_mutable_user_id();
  // @@protoc_insertion_point(field_mutable:sfu_rpc.QualityReport.user_id)
  return _s;
}
inline const std::string& QualityReport::_internal_user_id() const {
  return user_id_.Get();
}
inline void QualityReport::_internal_set_user_id(const std::string& value) {

  user_id_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArenaForAllocation());
}
inline std::string* QualityReport::_internal_mutable_user_id() {

  return user_id_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArenaForAllocation());
}
inline std::string* QualityReport::release_user_id() {
  // @@protoc_insertion_point(field_release:sfu_rpc.QualityReport.user_id)
  return user_id_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArenaForAllocation());
}
inline void QualityReport::set_allocated_user_id(std::string* user_id) {
  if (user_id != nullptr) {

  } else {

  }
  user_id_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), user_id,
      GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (user_id_.IsDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited())) {
    user_id_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), "", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:sfu_rpc.QualityReport.user_id)
}

// float packet_loss = 3;
inline void QualityReport::clear_packet_loss() {
  packet_loss_ = 0;
}
inline float QualityReport::_internal_packet_loss() const {
  return packet_loss_;
}
inline float QualityReport::packet_loss() const {
  // @@protoc_insertion_point(field_get:sfu_rpc.QualityReport.packet_loss)
  return _internal_packet_loss();
}
inline void QualityReport::_internal_set_packet_loss(float value) {

  packet_loss_ = value;
}
inline void QualityReport::set_packet_loss(float value) {
  _internal_set_packet_loss(value);
  // @@protoc_insertion_point(field_set:sfu_rpc.QualityReport.packet_loss)
}

// uint32 rtt_ms = 4;
inline void QualityReport::clear_rtt_ms() {
  rtt_ms_ = 0u;
}
inline uint32_t QualityReport::_internal_rtt_ms() const {
  return rtt_ms_;
}
inline uint32_t QualityReport::rtt_ms() const {
  // @@protoc_insertion_point(field_get:sfu_rpc.QualityReport.rtt_ms)
  return _internal_rtt_ms();
}
inline void QualityReport::_internal_set_rtt_ms(uint32_t value) {

  rtt_ms_ = value;
}
inline void QualityReport::set_rtt_ms(uint32_t value) {
  _internal_set_rtt_ms(value);
  // @@protoc_insertion_point(field_set:sfu_rpc.QualityReport.rtt_ms)
}

// uint32 jitter_ms = 5;
inline void QualityReport::clear_jitter_ms() {
  jitter_ms_ = 0u;
}
inline uint32_t QualityReport::_internal_jitter_ms() const {
  return jitter_ms_;
}
inline uint32_t QualityReport::jitter_ms() const {
  // @@protoc_insertion_point(field_get:sfu_rpc.QualityReport.jitter_ms)
  return _internal_jitter_ms();
}
inline void QualityReport::_internal_set_jitter_ms(uint32_t value) {

  jitter_ms_ = value;
}
inline void QualityReport::set_jitter_ms(uint32_t value) {
  _internal_set_jitter_ms(value);
  // @@protoc_insertion_point(field_set:sfu_rpc.QualityReport.jitter_ms)
}

// uint32 bitrate_kbps = 6;
inline void QualityReport::clear_bitrate_kbps() {
  bitrate_kbps_ = 0u;
}
inline uint32_t QualityReport::_internal_bitrate_kbps() const {
  return bitrate_kbps_;
}
inline uint32_t QualityReport::bitrate_kbps() const {
  // @@protoc_insertion_point(field_get:sfu_rpc.QualityReport.bitrate_kbps)
  return _internal_bitrate_kbps();
}
inline void QualityReport::_internal_set_bitrate_kbps(uint32_t value) {

  bitrate_kbps_ = value;
}
inline void QualityReport::set_bitrate_kbps(uint32_t value) {
  _internal_set_bitrate_kbps(value);
  // @@protoc_insertion_point(field_set:sfu_rpc.QualityReport.bitrate_kbps)
}

// -------------------------------------------------------------------

// KeyframeRequest

// string meeting_id = 1;
inline void KeyframeRequest::clear_meeting_id() {
  meeting_id_.ClearToEmpty();
}
inline const std::string& KeyframeRequest::meeting_id() const {
  // @@protoc_insertion_point(field_get:sfu_rpc.KeyframeRequest.meeting_id)
  return _internal_meeting_id();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void KeyframeRequest::set_meeting_id(ArgT0&& arg0, ArgT... args) {

 meeting_id_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:sfu_rpc.KeyframeRequest.meeting_id)
}
inline std::string* KeyframeRequest::mutable_meeting_id() {
  std::string* _s = _internal_mutable_meeting_id();
  // @@protoc_insertion_point(field_mutable:sfu_rpc.KeyframeRequest.meeting_id)
  return _s;
}
inline const std::string& KeyframeRequest::_internal_meeting_id() const {
  return meeting_id_.Get();
}
inline void KeyframeRequest::_internal_set_meeting_id(const std::string& value) {

  meeting_id_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArenaForAllocation());
}
inline std::string* KeyframeRequest::_internal_mutable_meeting_id() {

  return meeting_id_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArenaForAllocation());
}
inline std::string* KeyframeRequest::release_meeting_id() {
  // @@protoc_insertion_point(field_release:sfu_rpc.KeyframeRequest.meeting_id)
  return meeting_id_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArenaForAllocation());
}
inline void KeyframeRequest::set_allocated_meeting_id(std::string* meeting_id) {
  if (meeting_id != nullptr) {

  } else {

  }
  meeting_id_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), meeting_id,
      GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (meeting_id_.IsDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited())) {
    meeting_id_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), "", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:sfu_rpc.KeyframeRequest.meeting_id)
}

// string user_id = 2;
inline void KeyframeRequest::clear_user_id() {
  user_id_.ClearToEmpty();
}
inline const std::string& KeyframeRequest::user_id() const {
  // @@protoc_insertion_point(field_get:sfu_rpc.KeyframeRequest.user_id)
  return _internal_user_id();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void KeyframeRequest::set_user_id(ArgT0&& arg0, ArgT... args) {

 user_id_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:sfu_rpc.KeyframeRequest.user_id)
}
inline std::string* KeyframeRequest::mutable_user_id() {
  std::string* _s = _internal_mutable_user_id();
  // @@protoc_insertion_point(field_mutable:sfu_rpc.KeyframeRequest.user_id)
  return _s;
}
inline const std::string& KeyframeRequest::_internal_user_id() const {
  return user_id_.Get();
}
inline void KeyframeRequest::_internal_set_user_id(const std::string& value) {

  user_id_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArenaForAllocation());
}
inline std::string* KeyframeRequest::_internal_mutable_user_id() {

  return user_id_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArenaForAllocation());
}
inline std::string* KeyframeRequest::release_user_id() {
  // @@protoc_insertion_point(field_release:sfu_rpc.KeyframeRequest.user_id)
  return user_id_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArenaForAllocation());
}
inline void KeyframeRequest::set_allocated_user_id(std::string* user_id) {
  if (user_id != nullptr) {

  } else {

  }
  user_id_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), user_id,
      GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (user_id_.IsDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited())) {
    user_id_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), "", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:sfu_rpc.KeyframeRequest.user_id)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace sfu_rpc

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_sfu_5frpc_2eproto
